this is learning website
this-is-learning/this-is-learning-website pull request #12
Opened 2022-03-15 15:36 UTC by haroon786

2022-03-16 21:38 UTC, santoshyadavdev commented on angular.json
> +      "prefix": "this-is-learning",
keep this til

2022-03-16 21:41 UTC, santoshyadavdev commented on apps/this-is-learning/src/styles.scss
> +@import 'tailwindcss/utilities';
can you remove extra space, or run the prettier

2022-03-16 21:42 UTC, santoshyadavdev commented on libs/navbar/.eslintrc.json
> +            "prefix": "thisIsLearning",
keep til

2022-03-16 21:42 UTC, santoshyadavdev commented on libs/navbar/.eslintrc.json
> +            "prefix": "this-is-learning",
same here

2022-03-16 21:44 UTC, santoshyadavdev requested changes
Can you run prettier for all the files.

2022-03-26 10:43 UTC, santoshyadavdev approved these changes
thank you :)

2022-03-26 10:45 UTC, santoshyadavdev requested changes
Please check the prevois comments

2022-03-26 11:38 UTC, santoshyadavdev approved these changes
Thank you for making changes

2022-03-28 20:24 UTC, LayZeeDK requested changes

2022-03-28 20:24 UTC, LayZeeDK commented on apps/this-is-learning-e2e/src/integration/app.spec.ts
> +  //   getGreeting().contains('Hello, Scully!');
issue: Please keep at least one working end-to-end test (we're using Cypress)

2022-03-29 18:52 UTC, LayZeeDK requested changes
The end to end test is now failing, Haroon

2022-03-29 19:34 UTC, haroon786 commented
unfortunately, I have never written any test cases :(, now  it passed all checks

2022-03-29 19:36 UTC, santoshyadavdev approved these changes

2022-03-30 14:02 UTC, LayZeeDK requested changes
issue: Please consider whether we are directly using the `lightBlue` Tailwind variable
```
warn - As of Tailwind CSS v2.2, `lightBlue` has been renamed to `sky`.
warn - Please update your color palette to eliminate this warning.
```

2022-04-02 20:11 UTC, LayZeeDK approved these changes

2022-04-02 21:15 UTC, merged